@API_BASE_URL = http://localhost:5002
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTJhYThlNC0zZTNlLTQ1YzUtOGUwMy00MmYwZTQ5OTY0OWMiLCJlbWFpbCI6InplcnBhYW50aG9ueS53eEBicmVhZHJpdXNzLmNvbSIsInJvbGUiOiJwYXRpZW50IiwiaWF0IjoxNzc3NjY5NjU4LCJleHAiOjE3Nzc2NzY4NTh9.yeJBgElcYUf-4Bm--eTDWGdu0RKN2PiZJU3VMJqCIfQ
Content-Type: application/json

{
    "firstName": "Yoyo",
    "lastName": "Cursewl",
    "email": "hello@breadriuss.com",
    "password": "Jose1214#"
}


### Login
POST {{API_BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "zerpaanthony.wx@breadriuss.com",
    "password": "Jose1214#"
}

### Verificar token 
GET {{API_BASE_URL}}/auth/me
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}


### Recibir todos los endpoints uwu
GET {{API_BASE_URL}}/system/permissions
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}